CREATE TABLE `cadastro_pf` (
	`id` int AUTO_INCREMENT NOT NULL,
	`data_cadastro` datetime NOT NULL,
	`nome_completo` varchar(255) NOT NULL,
	`cpf` varchar(14) NOT NULL,
	`rg` varchar(15),
	`data_nascimento` datetime NOT NULL,
	`nome_mae` varchar(255) NOT NULL,
	`endereco` varchar(255) NOT NULL,
	`numero` varchar(20) NOT NULL,
	`bairro` varchar(100) NOT NULL,
	`cep` varchar(9) NOT NULL,
	`uf` varchar(2) NOT NULL,
	`cidade` varchar(100) NOT NULL,
	`rede_social` varchar(255),
	`telefone` varchar(15) NOT NULL,
	`email` varchar(255) NOT NULL,
	`ref1_empresa` varchar(255) NOT NULL,
	`ref1_contato` varchar(255) NOT NULL,
	`ref1_telefone` varchar(15) NOT NULL,
	`ref2_empresa` varchar(255),
	`ref2_contato` varchar(255),
	`ref2_telefone` varchar(15),
	`ref3_empresa` varchar(255),
	`ref3_contato` varchar(255),
	`ref3_telefone` varchar(15),
	`ocupacao` varchar(255),
	`ramo` varchar(255),
	`associacao` varchar(255),
	`qual_associacao` varchar(255),
	`nome_pai` varchar(255),
	`estudante` boolean NOT NULL,
	`cnh_valida` boolean NOT NULL,
	`rg_cnh_url` varchar(500),
	`cpf_cnh_url` varchar(500),
	`comprovant_residencia_url` varchar(500),
	`criado_em` datetime NOT NULL,
	`atualizado_em` datetime NOT NULL,
	`status` enum('pendente','aprovado','rejeitado') DEFAULT 'pendente',
	CONSTRAINT `cadastro_pf_id` PRIMARY KEY(`id`),
	CONSTRAINT `cadastro_pf_cpf_unique` UNIQUE(`cpf`)
);
--> statement-breakpoint
CREATE TABLE `cadastro_pj` (
	`id` int AUTO_INCREMENT NOT NULL,
	`data_cadastro` datetime NOT NULL,
	`contato` varchar(255) NOT NULL,
	`telefone` varchar(15) NOT NULL,
	`email` varchar(255) NOT NULL,
	`contato1_nome` varchar(255),
	`contato1_telefone` varchar(15),
	`contato1_empresa` varchar(255),
	`contato2_nome` varchar(255),
	`contato2_telefone` varchar(15),
	`contato2_empresa` varchar(255),
	`contato3_nome` varchar(255),
	`contato3_telefone` varchar(15),
	`contato3_empresa` varchar(255),
	`prop1_nome` varchar(255) NOT NULL,
	`prop1_data_nascimento` datetime NOT NULL,
	`prop1_rg` varchar(15) NOT NULL,
	`prop1_cpf` varchar(14) NOT NULL,
	`prop2_nome` varchar(255),
	`prop2_data_nascimento` datetime,
	`prop2_rg` varchar(15),
	`prop2_cpf` varchar(14),
	`ref1_empresa` varchar(255) NOT NULL,
	`ref1_contato` varchar(255) NOT NULL,
	`ref1_telefone` varchar(15) NOT NULL,
	`ref2_empresa` varchar(255),
	`ref2_contato` varchar(255),
	`ref2_telefone` varchar(15),
	`ref3_empresa` varchar(255),
	`ref3_contato` varchar(255),
	`ref3_telefone` varchar(15),
	`endereco` varchar(255) NOT NULL,
	`complemento` varchar(255),
	`bairro` varchar(100) NOT NULL,
	`cep` varchar(9) NOT NULL,
	`cidade` varchar(100) NOT NULL,
	`uf` varchar(2) NOT NULL,
	`ultima_alteracao_url` varchar(500),
	`cartao_cnpj_url` varchar(500),
	`comprovante_endereco_url` varchar(500),
	`criado_em` datetime NOT NULL,
	`atualizado_em` datetime NOT NULL,
	`status` enum('pendente','aprovado','rejeitado') DEFAULT 'pendente',
	CONSTRAINT `cadastro_pj_id` PRIMARY KEY(`id`)
);
